name: Global workflow to rule them all

on:
  push:
      branches: 
        - main

jobs:
  replicate-changes:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Replicating global workflows
        uses: derberg/global-workflows-support@v0.5.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          files_to_ignore: global-workflows-support.yml
          committer_username: vvdevteam
          committer_email: dev@vertigoventures.com
          commit_message: "ci: update global workflows"
          topics_to_include: "workflows"
